#+STARTUP: indent
#+TITLE: microinterface

#+OPTIONS: LaTeX:t          Do the right thing automatically (MathJax)
#+OPTIONS: LaTeX:dvipng     Force using dvipng images
#+OPTIONS: LaTeX:nil        Do not process LaTeX fragments at all
#+OPTIONS: LaTeX:verbatim   Verbatim export, for jsMath or so
#+ATTR_HTML: width="10in"

% org-export-with-LaTeX-fragments



README.org --- description



Copyright (C) 2013 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>



  This file is part of microinterface.

  microinterface is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  microinterface is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with microinterface.  If not, see <http://www.gnu.org/licenses/>.



* Keywords:
encoder interface display

* Description:
display (lcd), Encoder button, allow you to display and modify program settings  

* Usage:
use it



* History:
Project created at 2013-01(Jan)-26


* Dependences:
** hardware
- microcontroller(Arduino)
- display (in my case: OLED 16x2)
- encoder
- button
** software
- https://github.com/chujoii/encoder
- http://www.xs4all.nl/~hmario/arduino/LiquidCrystal_I2C
  
* Connection scheme

If you use optical (or another type of encoder/button with hardware PushUp),
then comment string with "PushUp" in file examples/simple_test/simple_test.ino

| pin number (Arduino) | connector    | comment  |
|----------------------+--------------+----------|
|                    2 | encoder1_a   |          |
|                  GND | encoder1_com |          |
|                    3 | encoder1_b   |          |
|                      |              |          |
|                    4 | button2      |          |
|                  GND | button2_com  |          |
|                      |              |          |
|                    5 | button3      | not used |
|                  GND | button3_com  | not used |

* Config
A rotary encoder includes a detent (a spring with bumps), that makes a
clicking sound as the shaft is turned. Detent corresponds to the 1, 2
or 4 encoder`s events.
